### ISSUE TITLE
Problem detecting number 1

### ISSUE THREAD

**Issue by abdallahalsamman** [jiweibo/SSOCR#3]
## Source Images
![img_20181210_095334 jpg](https://user-images.githubusercontent.com/12014839/49867719-ee42f780-fe13-11e8-9d29-f99ec7e2a34d.jpg)

![img_20181210_095349 jpg](https://user-images.githubusercontent.com/12014839/49867726-f307ab80-fe13-11e8-85f3-6301171177b8.jpg)

## Can't detect number one
<img width="542" alt="screen shot 2018-12-12 at 1 44 13 pm" src="https://user-images.githubusercontent.com/12014839/49867759-0e72b680-fe14-11e8-8d3a-dc7b76d1ee79.png">

<img width="542" alt="screen shot 2018-12-12 at 1 44 24 pm" src="https://user-images.githubusercontent.com/12014839/49867770-1a5e7880-fe14-11e8-9cc9-a55e1d1c836a.png">

**Comment by vishwesh2000** [comment]
Hey since this issue seems to be solved, can I get some insights on how this issue was solved? If digits on my image are not being recognized then should I make changes:
1. here? -
![image](https://user-images.githubusercontent.com/54475954/114009088-77ea1f00-9880-11eb-8ce6-8f290dcadb36.png)
**OR**
2. here (recognize_digits_area_method)? -
![image](https://user-images.githubusercontent.com/54475954/114009256-9c45fb80-9880-11eb-822a-73e72dab474a.png)
**OR**
3. here (recognize_digits_line_method)? -
![image](https://user-images.githubusercontent.com/54475954/114009537-dadbb600-9880-11eb-99cd-15b89540e0ec.png)
